# Project: TOYTL - GVM

# Target
BIN      = bin/gamevm_x64_exe

# Compiler settings
CXXFLAGS = -O3 -Wall -W -march=native -mfpmath=sse -fomit-frame-pointer -fno-exceptions -fexpensive-optimizations -D_GVM_HOST_OS=_GVM_HOST_LINUX_INTEL_64 -D_GVM_DEBUGGING_ -D_GVM_DEBUG_FUNCTIONS_ -D_GVM_DEBUG_OPCODES_

# Makefile settings
ARCH     = x64_linux
MEXT     = $(ARCH)

include interpreter.make

