#!/usr/bin/php
<?php

if (!isset($_SERVER['argv'][1])) {
    echo "Usage: ./asm <path to project>\n";
    exit();
}
$sProjectPath = trim($_SERVER['argv'][1]);

foreach (glob('php/*.php') as $sInclude) {
    require_once($sInclude);
}

$oAssebler = new Assembler(
    new AssemblerConfig("config/config.json"),
    new SourceLoader(
        new Project($sProjectPath.'project.json')
    )
);
$oAssebler->assemble();
